window.EXAM_QUESTION_BANK = {
  meta: {
    project: "test.ingles",
    generatedFrom: [
      "img/hoja1.jpeg",
      "img/hoja2.jpeg",
      "img/hoja3.jpeg",
      "img/hoja4.jpeg"
    ],
    generatedBy: "visual-extraction-v1",
    note: "Banco separado del codigo principal. Las imagenes son la fuente documental y no se muestran al alumno.",
    reviewItems: [
      {
        source: "img/hoja2.jpeg",
        section: "Complete the words and phrases",
        reason: "Varias palabras con letras omitidas no se leen con fiabilidad suficiente en la imagen."
      },
      {
        source: "img/hoja4.jpeg",
        section: "Functional Language 2",
        reason: "Algunas respuestas manuscritas tapan parte del texto. Se han incluido solo las preguntas legibles."
      }
    ]
  },
  vocabulary: [
    { word: "carrier", meaning: "transportista", explanation: "Empresa o persona que transporta mercancia.", example: "The carrier will deliver the pallets tomorrow." },
    { word: "shipper", meaning: "remitente", explanation: "Persona o empresa que envia la mercancia.", example: "The shipper prepared the export documents." },
    { word: "freight", meaning: "mercancia / carga", explanation: "Productos transportados por carretera, barco, avion o tren.", example: "The freight arrived at the warehouse this morning." },
    { word: "warehouse", meaning: "almacen", explanation: "Lugar donde se guardan productos antes de venderlos o enviarlos.", example: "The goods are stored in the warehouse." },
    { word: "goods in", meaning: "entrada de mercancia", explanation: "Zona o proceso donde se recibe mercancia.", example: "Take the delivery to Goods In." },
    { word: "goods out", meaning: "salida de mercancia", explanation: "Zona o proceso donde salen los pedidos preparados.", example: "The order is ready in Goods Out." },
    { word: "dispatch", meaning: "enviar / despachar", explanation: "Enviar un pedido desde el almacen al cliente.", example: "We dispatch orders every afternoon." },
    { word: "consignee", meaning: "destinatario", explanation: "Persona o empresa que recibe la mercancia.", example: "The consignee is Ace Electronics." },
    { word: "container", meaning: "contenedor", explanation: "Unidad grande usada para transportar carga.", example: "The container is waiting at the port." },
    { word: "in stock", meaning: "en stock", explanation: "Disponible en almacen para vender o enviar.", example: "This item is in stock." },
    { word: "out of stock", meaning: "agotado", explanation: "No disponible en ese momento.", example: "That watch is out of stock." },
    { word: "bulk", meaning: "al por mayor", explanation: "Comprar o mover grandes cantidades.", example: "We buy in bulk." },
    { word: "label", meaning: "etiquetar", explanation: "Poner una etiqueta con informacion del producto o envio.", example: "Label every box before dispatch." },
    { word: "weigh", meaning: "pesar", explanation: "Medir el peso de un producto o paquete.", example: "Weigh the boxes before shipping." },
    { word: "pallet", meaning: "pale", explanation: "Base de madera o plastico para mover mercancia.", example: "The box is on that pallet." },
    { word: "forklift", meaning: "carretilla elevadora", explanation: "Vehiculo para levantar y mover pales.", example: "Load the boxes with a forklift." },
    { word: "wooden crate", meaning: "caja de madera", explanation: "Caja resistente para proteger productos.", example: "Use a wooden crate for fragile goods." },
    { word: "conveyor belt", meaning: "cinta transportadora", explanation: "Sistema que mueve productos de un punto a otro.", example: "The boxes move along the conveyor belt." },
    { word: "showroom", meaning: "sala de exposicion", explanation: "Espacio donde se muestran productos a clientes.", example: "Visit our showroom to see the items." },
    { word: "order picking", meaning: "preparacion de pedidos", explanation: "Proceso de recoger productos del almacen para un pedido.", example: "Order picking starts at eight o'clock." },
    { word: "expiry date", meaning: "fecha de caducidad", explanation: "Fecha limite para usar o vender un producto.", example: "Check the expiry date." },
    { word: "SKU code", meaning: "codigo SKU", explanation: "Codigo unico para identificar un producto.", example: "Use the SKU code for this item." },
    { word: "handling charges", meaning: "gastos de manipulacion", explanation: "Costes por preparar, mover o gestionar mercancia.", example: "Handling charges are low." },
    { word: "cost price", meaning: "precio de coste", explanation: "Precio que paga la empresa por comprar el producto.", example: "The cost price is 250 pounds." },
    { word: "retail price", meaning: "precio de venta", explanation: "Precio final que paga el cliente.", example: "What is the retail price?" },
    { word: "profit", meaning: "beneficio", explanation: "Dinero que queda despues de restar costes.", example: "We do not make much profit." },
    { word: "importer", meaning: "importador", explanation: "Empresa que compra productos de otro pais.", example: "Eastern Bazaar is an importer of goods from Asia." },
    { word: "duty free", meaning: "libre de impuestos", explanation: "Sin pagar ciertos impuestos de importacion o venta.", example: "The goods are duty free." },
    { word: "road haulage", meaning: "transporte por carretera", explanation: "Transporte de mercancia en camion.", example: "Road haulage is cheaper than air freight." },
    { word: "paperwork", meaning: "documentacion", explanation: "Documentos necesarios para compras, ventas o envios.", example: "There is a lot of paperwork to complete." }
  ],
  questions: [
    {
      id: 1,
      source: "img/hoja1.jpeg",
      section: "Vocabulary",
      type: "multiple_choice",
      question: "Where is our freight container?",
      options: ["I don't know. I'll talk to the shipper.", "I don't know. I'll talk to the carrier.", "Both a and b."],
      correct: 2,
      translation: "Donde esta nuestro contenedor de mercancias?",
      hint: "Puede tener informacion quien envia y quien transporta.",
      explanation: "La respuesta correcta es 'Both a and b' porque tanto el remitente como el transportista pueden tener informacion sobre el contenedor.",
      vocabulary: [{ word: "freight container", meaning: "contenedor de mercancias" }, { word: "shipper", meaning: "remitente" }, { word: "carrier", meaning: "transportista" }]
    },
    {
      id: 2,
      source: "img/hoja1.jpeg",
      section: "Vocabulary",
      type: "multiple_choice",
      question: "How can you sell these cameras so cheaply?",
      options: ["We follow trends.", "We buy in bulk.", "Both a and b."],
      correct: 1,
      translation: "Como podeis vender estas camaras tan baratas?",
      hint: "La respuesta habla de comprar mucha cantidad.",
      explanation: "'We buy in bulk' significa que compran al por mayor, por eso pueden vender mas barato.",
      vocabulary: [{ word: "buy in bulk", meaning: "comprar al por mayor" }, { word: "cheaply", meaning: "barato / a bajo precio" }]
    },
    {
      id: 3,
      source: "img/hoja1.jpeg",
      section: "Vocabulary",
      type: "multiple_choice",
      question: "Where can I see the goods that have just arrived?",
      options: ["In the Goods In department.", "In the Goods Out department.", "Both a and b."],
      correct: 0,
      translation: "Donde puedo ver la mercancia que acaba de llegar?",
      hint: "La mercancia acaba de entrar.",
      explanation: "'Goods In' es la zona de entrada de mercancia, por eso es la respuesta correcta.",
      vocabulary: [{ word: "Goods In", meaning: "entrada de mercancia" }, { word: "arrived", meaning: "llegado" }]
    },
    {
      id: 4,
      source: "img/hoja1.jpeg",
      section: "Vocabulary",
      type: "multiple_choice",
      question: "Do you sell a lot of products in Ireland?",
      options: ["Yes, we've got a very good distributor there.", "Yes, we've got a very good freight container there.", "Both a and b."],
      correct: 0,
      translation: "Vendeis muchos productos en Irlanda?",
      hint: "Para vender en un pais necesitas un canal comercial, no un contenedor.",
      explanation: "Un 'distributor' puede ayudar a vender productos en Irlanda. Un 'freight container' es solo un contenedor de transporte.",
      vocabulary: [{ word: "distributor", meaning: "distribuidor" }, { word: "freight container", meaning: "contenedor de mercancias" }]
    },
    {
      id: 5,
      source: "img/hoja1.jpeg",
      section: "Vocabulary",
      type: "multiple_choice",
      question: "These boxes haven't got the customer's address on them.",
      options: ["I'll weigh them now.", "I'll label them now.", "Both a and b."],
      correct: 1,
      translation: "Estas cajas no tienen la direccion del cliente.",
      hint: "Falta informacion escrita en la caja.",
      explanation: "Si faltan datos como la direccion, hay que etiquetar las cajas. 'Weigh' significa pesar, no poner direccion.",
      vocabulary: [{ word: "label", meaning: "etiquetar" }, { word: "customer's address", meaning: "direccion del cliente" }]
    },
    {
      id: 6,
      source: "img/hoja1.jpeg",
      section: "Choose the correct word",
      type: "word_choice",
      question: "I'm sorry. We haven't got that item ____.",
      options: ["demand", "in stock", "validity"],
      correct: 1,
      translation: "Lo siento. No tenemos ese articulo en stock.",
      hint: "Busca la expresion de disponibilidad.",
      explanation: "'In stock' significa disponible. La frase negativa indica que no lo tienen disponible.",
      vocabulary: [{ word: "in stock", meaning: "en stock" }, { word: "item", meaning: "articulo" }]
    },
    {
      id: 7,
      source: "img/hoja1.jpeg",
      section: "Choose the correct word",
      type: "word_choice",
      question: "Can you ____ these boxes on that rack?",
      options: ["stack", "pick", "dispatch"],
      correct: 0,
      translation: "Puedes apilar estas cajas en esa estanteria?",
      hint: "La accion se hace sobre cajas en una estanteria.",
      explanation: "'Stack' significa apilar. Es la accion correcta con cajas y racks.",
      vocabulary: [{ word: "stack", meaning: "apilar" }, { word: "rack", meaning: "estanteria / rack" }]
    },
    {
      id: 8,
      source: "img/hoja1.jpeg",
      section: "Choose the correct word",
      type: "word_choice",
      question: "Some of the goods are ____.",
      options: ["damaged", "excess", "cargo"],
      correct: 0,
      translation: "Parte de la mercancia esta danada.",
      hint: "La frase necesita un adjetivo que describa mal estado.",
      explanation: "'Damaged' significa danado. 'Cargo' es carga y 'excess' es exceso.",
      vocabulary: [{ word: "damaged", meaning: "danado" }, { word: "goods", meaning: "mercancia" }]
    },
    {
      id: 9,
      source: "img/hoja1.jpeg",
      section: "Choose the correct word",
      type: "word_choice",
      question: "Have you got excess ____ cover?",
      options: ["insurance", "merchandise", "conveyor belt"],
      correct: 0,
      translation: "Tienes cobertura de seguro adicional?",
      hint: "La palabra 'cover' suele relacionarse con proteccion o seguro.",
      explanation: "'Insurance cover' significa cobertura de seguro.",
      vocabulary: [{ word: "insurance cover", meaning: "cobertura de seguro" }]
    },
    {
      id: 10,
      source: "img/hoja1.jpeg",
      section: "Choose the correct word",
      type: "word_choice",
      question: "You can visit our ____ to see the different items we sell.",
      options: ["showroom", "order picking department", "consignee"],
      correct: 0,
      translation: "Puedes visitar nuestra sala de exposicion para ver los articulos que vendemos.",
      hint: "Es un lugar donde se muestran productos.",
      explanation: "'Showroom' es una sala de exposicion.",
      vocabulary: [{ word: "showroom", meaning: "sala de exposicion" }, { word: "items", meaning: "articulos" }]
    },
    {
      id: 11,
      source: "img/hoja1.jpeg",
      section: "Match phrases",
      type: "match",
      question: "Which phrase is correct?",
      options: ["expiry date", "expiry price", "expiry seller"],
      correct: 0,
      translation: "Que combinacion es correcta?",
      hint: "Se usa en productos con caducidad.",
      explanation: "La combinacion correcta es 'expiry date', fecha de caducidad.",
      vocabulary: [{ word: "expiry date", meaning: "fecha de caducidad" }]
    },
    {
      id: 12,
      source: "img/hoja1.jpeg",
      section: "Match phrases",
      type: "match",
      question: "Which phrase is correct?",
      options: ["SKU code", "SKU charges", "SKU seller"],
      correct: 0,
      translation: "Que combinacion es correcta?",
      hint: "SKU identifica un producto con un codigo.",
      explanation: "La combinacion correcta es 'SKU code', codigo SKU.",
      vocabulary: [{ word: "SKU code", meaning: "codigo SKU" }]
    },
    {
      id: 13,
      source: "img/hoja1.jpeg",
      section: "Match phrases",
      type: "match",
      question: "Which phrase is correct?",
      options: ["slow seller", "slow price", "slow date"],
      correct: 0,
      translation: "Que combinacion es correcta?",
      hint: "Describe un producto que se vende despacio.",
      explanation: "'Slow seller' es un producto que se vende lentamente.",
      vocabulary: [{ word: "slow seller", meaning: "producto de venta lenta" }]
    },
    {
      id: 14,
      source: "img/hoja1.jpeg",
      section: "Match phrases",
      type: "match",
      question: "Which phrase is correct?",
      options: ["handling charges", "handling code", "handling seller"],
      correct: 0,
      translation: "Que combinacion es correcta?",
      hint: "Son costes asociados a preparar o mover mercancia.",
      explanation: "'Handling charges' son gastos de manipulacion.",
      vocabulary: [{ word: "handling charges", meaning: "gastos de manipulacion" }]
    },
    {
      id: 15,
      source: "img/hoja1.jpeg",
      section: "Match phrases",
      type: "match",
      question: "Which phrase is correct?",
      options: ["cost price", "cost code", "cost list"],
      correct: 0,
      translation: "Que combinacion es correcta?",
      hint: "Es el precio antes de vender al cliente.",
      explanation: "'Cost price' es el precio de coste.",
      vocabulary: [{ word: "cost price", meaning: "precio de coste" }]
    },
    {
      id: 16,
      source: "img/hoja1.jpeg",
      section: "Match phrases",
      type: "match",
      question: "Which phrase is correct?",
      options: ["picking list", "picking charges", "picking date"],
      correct: 0,
      translation: "Que combinacion es correcta?",
      hint: "Se usa para preparar pedidos.",
      explanation: "'Picking list' es una lista de preparacion de pedidos.",
      vocabulary: [{ word: "picking list", meaning: "lista de preparacion de pedidos" }]
    },
    {
      id: 17,
      source: "img/hoja3.jpeg",
      section: "Correct the sentence",
      type: "word_choice",
      question: "Please help Ed to negotiate the lorry with these boxes.",
      options: ["load", "lend", "label"],
      correct: 0,
      translation: "Ayuda a Ed a cargar el camion con estas cajas.",
      hint: "La frase necesita una accion fisica con cajas y un camion.",
      explanation: "La palabra correcta es 'load'. No se negocia un camion con cajas; se carga.",
      vocabulary: [{ word: "load", meaning: "cargar" }, { word: "lorry", meaning: "camion" }]
    },
    {
      id: 18,
      source: "img/hoja3.jpeg",
      section: "Correct the sentence",
      type: "word_choice",
      question: "The vessel for this order is Ace Electronics in Bradford.",
      options: ["consignee", "container", "carrier"],
      correct: 0,
      translation: "El destinatario de este pedido es Ace Electronics en Bradford.",
      hint: "Ace Electronics es quien recibe el pedido.",
      explanation: "La palabra correcta es 'consignee', destinatario. 'Vessel' significa buque.",
      vocabulary: [{ word: "consignee", meaning: "destinatario" }, { word: "vessel", meaning: "buque" }]
    },
    {
      id: 19,
      source: "img/hoja3.jpeg",
      section: "Correct the sentence",
      type: "word_choice",
      question: "It's sometimes difficult to dispatch which items customers will like.",
      options: ["predict", "load", "mark down"],
      correct: 0,
      translation: "A veces es dificil predecir que articulos gustaran a los clientes.",
      hint: "La frase habla de anticipar algo.",
      explanation: "La palabra correcta es 'predict'. 'Dispatch' significa enviar.",
      vocabulary: [{ word: "predict", meaning: "predecir" }, { word: "dispatch", meaning: "enviar / despachar" }]
    },
    {
      id: 20,
      source: "img/hoja3.jpeg",
      section: "Correct the sentence",
      type: "word_choice",
      question: "Try to load a good price when you meet the supplier.",
      options: ["negotiate", "weigh", "dispatch"],
      correct: 0,
      translation: "Intenta negociar un buen precio cuando te reunas con el proveedor.",
      hint: "La frase habla de conseguir un precio.",
      explanation: "La palabra correcta es 'negotiate'. Se negocia un precio, no se carga.",
      vocabulary: [{ word: "negotiate", meaning: "negociar" }, { word: "supplier", meaning: "proveedor" }]
    },
    {
      id: 21,
      source: "img/hoja3.jpeg",
      section: "Correct the sentence",
      type: "word_choice",
      question: "The company will predict the container next week.",
      options: ["dispatch", "consignee", "retail"],
      correct: 0,
      translation: "La empresa enviara el contenedor la semana que viene.",
      hint: "La frase necesita un verbo de envio.",
      explanation: "La palabra correcta es 'dispatch', enviar o despachar.",
      vocabulary: [{ word: "dispatch", meaning: "enviar / despachar" }, { word: "container", meaning: "contenedor" }]
    },
    {
      id: 22,
      source: "img/hoja3.jpeg",
      section: "Correct the sentence",
      type: "word_choice",
      question: "Which port will the consignee arrive in?",
      options: ["vessel", "paperwork", "showroom"],
      correct: 0,
      translation: "A que puerto llegara el buque?",
      hint: "A un puerto llega un medio de transporte, no el destinatario.",
      explanation: "La palabra correcta es 'vessel', buque. 'Consignee' es el destinatario.",
      vocabulary: [{ word: "vessel", meaning: "buque" }, { word: "consignee", meaning: "destinatario" }]
    },
    {
      id: 23,
      source: "img/hoja2.jpeg",
      section: "Complete sentences",
      type: "fill_blank",
      question: "Eastern Bazaar is a large ____ of goods from Asia.",
      options: ["importer", "pallet", "paperwork"],
      correct: 0,
      translation: "Eastern Bazaar es un gran importador de productos de Asia.",
      hint: "Compra productos de otro pais o region.",
      explanation: "'Importer' significa importador.",
      vocabulary: [{ word: "importer", meaning: "importador" }, { word: "goods", meaning: "mercancia / productos" }]
    },
    {
      id: 24,
      source: "img/hoja2.jpeg",
      section: "Complete sentences",
      type: "fill_blank",
      question: "We don't make much ____ on those computer screens.",
      options: ["profit", "road haulage", "cardboard box"],
      correct: 0,
      translation: "No ganamos mucho beneficio con esas pantallas de ordenador.",
      hint: "Habla de dinero ganado.",
      explanation: "'Profit' significa beneficio.",
      vocabulary: [{ word: "profit", meaning: "beneficio" }]
    },
    {
      id: 25,
      source: "img/hoja2.jpeg",
      section: "Complete sentences",
      type: "fill_blank",
      question: "It's cheaper to send the order by ____ than by air.",
      options: ["road haulage", "retail", "out of stock"],
      correct: 0,
      translation: "Es mas barato enviar el pedido por carretera que por avion.",
      hint: "Se compara con transporte aereo.",
      explanation: "'Road haulage' es transporte por carretera.",
      vocabulary: [{ word: "road haulage", meaning: "transporte por carretera" }, { word: "by air", meaning: "por avion" }]
    },
    {
      id: 26,
      source: "img/hoja2.jpeg",
      section: "Complete sentences",
      type: "fill_blank",
      question: "I'm afraid that particular watch is ____. Perhaps you'd like something else?",
      options: ["out of stock", "duty free", "worldwide service"],
      correct: 0,
      translation: "Me temo que ese reloj concreto esta agotado. Quizas quiera otra cosa.",
      hint: "No esta disponible.",
      explanation: "'Out of stock' significa agotado.",
      vocabulary: [{ word: "out of stock", meaning: "agotado" }]
    },
    {
      id: 27,
      source: "img/hoja2.jpeg",
      section: "Complete sentences",
      type: "fill_blank",
      question: "There is a lot of ____ to complete when you send an order abroad.",
      options: ["paperwork", "pallet", "retail"],
      correct: 0,
      translation: "Hay mucha documentacion que completar cuando envias un pedido al extranjero.",
      hint: "Son documentos y formularios.",
      explanation: "'Paperwork' significa documentacion o papeleo.",
      vocabulary: [{ word: "paperwork", meaning: "documentacion" }, { word: "abroad", meaning: "al extranjero" }]
    },
    {
      id: 28,
      source: "img/hoja2.jpeg",
      section: "Complete sentences",
      type: "fill_blank",
      question: "The box you're looking for is on that ____.",
      options: ["pallet", "importer", "profit"],
      correct: 0,
      translation: "La caja que buscas esta en ese pale.",
      hint: "Es una base donde se colocan cajas.",
      explanation: "'Pallet' significa pale.",
      vocabulary: [{ word: "pallet", meaning: "pale" }]
    },
    {
      id: 29,
      source: "img/hoja2.jpeg",
      section: "Complete sentences",
      type: "fill_blank",
      question: "We could send the goods to Hong Kong with Four Winds. They offer a ____.",
      options: ["worldwide service", "cardboard box", "cost price"],
      correct: 0,
      translation: "Podriamos enviar la mercancia a Hong Kong con Four Winds. Ofrecen un servicio mundial.",
      hint: "Hong Kong implica un servicio internacional.",
      explanation: "'Worldwide service' significa servicio mundial o internacional.",
      vocabulary: [{ word: "worldwide service", meaning: "servicio mundial" }]
    },
    {
      id: 30,
      source: "img/hoja2.jpeg",
      section: "Complete sentences",
      type: "fill_blank",
      question: "It's cheaper to buy goods abroad when they're ____.",
      options: ["duty free", "out of stock", "paperwork"],
      correct: 0,
      translation: "Es mas barato comprar productos en el extranjero cuando estan libres de impuestos.",
      hint: "No se pagan ciertos impuestos.",
      explanation: "'Duty free' significa libre de impuestos.",
      vocabulary: [{ word: "duty free", meaning: "libre de impuestos" }, { word: "abroad", meaning: "en el extranjero" }]
    },
    {
      id: 31,
      source: "img/hoja2.jpeg",
      section: "Complete sentences",
      type: "fill_blank",
      question: "Is it safe to send those goods in a ____?",
      options: ["cardboard box", "road haulage", "profit"],
      correct: 0,
      translation: "Es seguro enviar esos productos en una caja de carton?",
      hint: "La frase pide un embalaje.",
      explanation: "'Cardboard box' significa caja de carton.",
      vocabulary: [{ word: "cardboard box", meaning: "caja de carton" }]
    },
    {
      id: 32,
      source: "img/hoja2.jpeg",
      section: "Functional Language",
      type: "multiple_choice",
      question: "How soon can you supply me with the product?",
      options: ["Within two weeks.", "At the beginning of next month.", "Both a and b."],
      correct: 2,
      translation: "En cuanto tiempo puedes suministrarme el producto?",
      hint: "Las dos respuestas indican un plazo posible.",
      explanation: "Ambas respuestas contestan correctamente a 'How soon'.",
      vocabulary: [{ word: "supply", meaning: "suministrar" }, { word: "within", meaning: "dentro de" }]
    },
    {
      id: 33,
      source: "img/hoja2.jpeg",
      section: "Functional Language",
      type: "multiple_choice",
      question: "How much will it cost to send a container to Portugal?",
      options: ["The estimated time for this route is one week.", "Shipping fees are 600 for a full load.", "Both a and b."],
      correct: 1,
      translation: "Cuanto costara enviar un contenedor a Portugal?",
      hint: "La pregunta pide precio, no tiempo.",
      explanation: "'Shipping fees are 600' responde al coste. La primera opcion responde al tiempo.",
      vocabulary: [{ word: "shipping fees", meaning: "gastos de envio" }, { word: "full load", meaning: "carga completa" }]
    },
    {
      id: 34,
      source: "img/hoja2.jpeg",
      section: "Functional Language",
      type: "multiple_choice",
      question: "What do I do with my completed order?",
      options: ["Take it to the Goods In department.", "Take it to the Packing department.", "Both a and b."],
      correct: 1,
      translation: "Que hago con mi pedido completado?",
      hint: "Si ya esta completado, debe prepararse para envio.",
      explanation: "La opcion correcta es llevarlo al departamento de embalaje o packing.",
      vocabulary: [{ word: "completed order", meaning: "pedido completado" }, { word: "Packing department", meaning: "departamento de embalaje" }]
    },
    {
      id: 35,
      source: "img/hoja2.jpeg",
      section: "Functional Language",
      type: "multiple_choice",
      question: "Is there a discount if we buy in bulk?",
      options: ["It's 25% for orders of over 100 units.", "Not if you buy a lot of items.", "Both a and b."],
      correct: 0,
      translation: "Hay descuento si compramos al por mayor?",
      hint: "Busca una respuesta con descuento real.",
      explanation: "La primera respuesta da un descuento concreto para pedidos de mas de 100 unidades.",
      vocabulary: [{ word: "discount", meaning: "descuento" }, { word: "buy in bulk", meaning: "comprar al por mayor" }]
    },
    {
      id: 36,
      source: "img/hoja2.jpeg",
      section: "Functional Language",
      type: "multiple_choice",
      question: "How many boxes of pens have we got in stock?",
      options: ["We've run out of pens.", "About eight.", "Both a and b."],
      correct: 1,
      translation: "Cuantas cajas de boligrafos tenemos en stock?",
      hint: "La pregunta pide una cantidad.",
      explanation: "'About eight' responde con una cantidad aproximada.",
      vocabulary: [{ word: "in stock", meaning: "en stock" }, { word: "about", meaning: "aproximadamente" }]
    },
    {
      id: 37,
      source: "img/hoja2.jpeg",
      section: "Functional Language",
      type: "multiple_choice",
      question: "What's the credit limit on the order?",
      options: ["It's 5,000.", "Sorry, you have to pay upfront.", "Both a and b."],
      correct: 1,
      translation: "Cual es el limite de credito del pedido?",
      hint: "Si hay que pagar por adelantado, no se concede credito.",
      explanation: "La respuesta del ejercicio indica que hay que pagar por adelantado: 'pay upfront'.",
      vocabulary: [{ word: "credit limit", meaning: "limite de credito" }, { word: "pay upfront", meaning: "pagar por adelantado" }]
    },
    {
      id: 38,
      source: "img/hoja2.jpeg",
      section: "Functional Language",
      type: "multiple_choice",
      question: "How do I know where to put each pallet?",
      options: ["Each rack is labelled with a product code.", "Complete the daily log book.", "Both a and b."],
      correct: 0,
      translation: "Como se donde poner cada pale?",
      hint: "La respuesta debe ayudar a localizar el sitio.",
      explanation: "Las etiquetas de los racks con codigos de producto indican donde colocar cada pale.",
      vocabulary: [{ word: "rack", meaning: "estanteria / rack" }, { word: "labelled", meaning: "etiquetado" }]
    },
    {
      id: 39,
      source: "img/hoja2.jpeg",
      section: "Functional Language",
      type: "multiple_choice",
      question: "How long will it take to arrive?",
      options: ["It will be in a 20-foot container.", "The estimated shipping time is two to three weeks.", "Both a and b."],
      correct: 1,
      translation: "Cuanto tardara en llegar?",
      hint: "La pregunta pide duracion.",
      explanation: "La opcion correcta da un tiempo estimado de envio: dos o tres semanas.",
      vocabulary: [{ word: "estimated shipping time", meaning: "tiempo estimado de envio" }, { word: "arrive", meaning: "llegar" }]
    },
    {
      id: 40,
      source: "img/hoja2.jpeg",
      section: "Functional Language",
      type: "multiple_choice",
      question: "Are we sold out of any goods?",
      options: ["We ran out of sun hats this afternoon.", "Please mark down the stock we have.", "Both a and b."],
      correct: 0,
      translation: "Se nos ha agotado alguna mercancia?",
      hint: "'Run out of' significa quedarse sin algo.",
      explanation: "'We ran out of sun hats' significa que se agotaron los sombreros.",
      vocabulary: [{ word: "sold out", meaning: "agotado" }, { word: "run out of", meaning: "quedarse sin" }]
    },
    {
      id: 41,
      source: "img/hoja2.jpeg",
      section: "Functional Language",
      type: "multiple_choice",
      question: "Do I have to pay extra for insurance?",
      options: ["No, it's included in our price.", "No, it's included in our paperwork.", "Both a and b."],
      correct: 0,
      translation: "Tengo que pagar extra por el seguro?",
      hint: "La respuesta debe hablar de precio.",
      explanation: "Si el seguro esta incluido en el precio, no hay que pagar extra.",
      vocabulary: [{ word: "insurance", meaning: "seguro" }, { word: "included in our price", meaning: "incluido en nuestro precio" }]
    },
    {
      id: 42,
      source: "img/hoja4.jpeg",
      section: "Functional Language 2",
      type: "multiple_choice",
      question: "Are you good at working in marketing?",
      options: ["I'm conscientious and responsible. I'm also very outgoing.", "I worked in marketing at Excel Motors for one year.", "Great! When do I start?"],
      correct: 1,
      translation: "Se te da bien trabajar en marketing?",
      hint: "Busca una respuesta relacionada con experiencia en marketing.",
      explanation: "La respuesta mas adecuada habla de experiencia laboral en marketing.",
      vocabulary: [{ word: "marketing", meaning: "marketing" }, { word: "worked", meaning: "trabaje" }]
    },
    {
      id: 43,
      source: "img/hoja4.jpeg",
      section: "Functional Language 2",
      type: "multiple_choice",
      question: "Can you tell me about your educational background?",
      options: ["I'm glad to be back.", "I finished secondary school in 2014 and did a one-year vocational course in sales and marketing.", "We want happy there, but I wanted to move on."],
      correct: 1,
      translation: "Puedes hablarme de tu formacion academica?",
      hint: "Busca estudios o formacion.",
      explanation: "La respuesta correcta explica estudios y formacion profesional.",
      vocabulary: [{ word: "educational background", meaning: "formacion academica" }, { word: "vocational course", meaning: "curso profesional" }]
    },
    {
      id: 44,
      source: "img/hoja4.jpeg",
      section: "Functional Language 2",
      type: "multiple_choice",
      question: "What salary can I expect?",
      options: ["The starting salary is 18,000 per annum.", "That's OK. I can be flexible about my time.", "Great! When do I start?"],
      correct: 0,
      translation: "Que salario puedo esperar?",
      hint: "Busca una cantidad anual.",
      explanation: "La respuesta correcta indica el salario inicial anual.",
      vocabulary: [{ word: "salary", meaning: "salario" }, { word: "per annum", meaning: "al ano" }]
    },
    {
      id: 45,
      source: "img/hoja4.jpeg",
      section: "Functional Language 2",
      type: "multiple_choice",
      question: "What are my chances of advancement?",
      options: ["After one year you can apply for promotion.", "I'm David Connor. Pleased to meet you.", "That's OK. I can be flexible about my time."],
      correct: 0,
      translation: "Que posibilidades tengo de progresar?",
      hint: "Busca promocion o crecimiento.",
      explanation: "La respuesta correcta habla de solicitar promocion despues de un ano.",
      vocabulary: [{ word: "advancement", meaning: "progreso / ascenso" }, { word: "promotion", meaning: "promocion / ascenso" }]
    }
  ]
};
